# Generated by Django 5.1.3 on 2024-12-13 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_enrollment_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
